# Generated by Django 4.2.6 on 2023-11-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentarticles',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='studentarticles',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='studentarticles',
            index=models.Index(fields=['-time_create'], name='itclub_stud_time_cr_ba4e23_idx'),
        ),
    ]
