# Generated by Django 4.2.6 on 2023-11-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itclub', '0002_alter_studentarticles_options_studentarticles_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentarticles',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
