# Generated by Django 4.2.6 on 2023-11-23 08:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('itclub', '0003_alter_studentarticles_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentarticles',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='studentarticles',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
