# Generated by Django 4.2.6 on 2023-11-30 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itclub', '0005_category_studentarticles_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentarticles',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='itclub.category'),
        ),
    ]
