# Generated by Django 4.2.6 on 2023-12-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itclub', '0007_tagpost_studentarticles_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(blank=True)),
                ('post_length', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentarticles',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='itclub.tagpost'),
        ),
        migrations.AddField(
            model_name='studentarticles',
            name='summary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_post', to='itclub.summary'),
        ),
    ]
